# Example solver resource; override as you see fit.
apiVersion: org.optaplanner.solver/v1alpha1
kind: Solver
metadata:
  name: school-timetabling
spec:
  amqBroker:
    host: ex-aao-amqp-0-svc.demo.svc.cluster.local
    port: 5672
    managementHost: ex-aao-hdls-svc.demo.svc.cluster.local
    usernameSecretRef:
      key: AMQ_USER
      name: ex-aao-credentials-secret
    passwordSecretRef:
      key: AMQ_PASSWORD
      name: ex-aao-credentials-secret
  template:
    spec:
      containers:
        - name: school-timetabling
          image: quay.io/optaplanner/school-timetabling:latest
          imagePullPolicy: Never
  scaling:
    dynamic: true
    replicas: 3