environments:
  native:
    env_vars:
      NATIVE: true
      BUILD_MVN_OPTS_CURRENT: -Dnative -Dquarkus.native.container-build=true
      ADDITIONAL_TIMEOUT: 720
    ids:
    - native
  quarkus-main:
    env_vars:
      QUARKUS_BRANCH: main
    ids:
    - quarkus
    enabled: false
  quarkus-branch:
    env_vars:
      QUARKUS_BRANCH: '3.0'
      QUARKUS_VERSION: 999-jakarta-SNAPSHOT
    ids:
    - quarkus
  quarkus-lts:
    enabled: false
    env_vars:
      BUILD_MVN_OPTS: -Dproductized
      QUARKUS_BRANCH: '2.13'
    ids:
    - quarkus
    - lts
    - prod
  native-lts:
    enabled: false
    env_vars:
      NATIVE: true
      BUILD_MVN_OPTS: -Dproductized
      BUILD_MVN_OPTS_CURRENT: -Dnative -Dquarkus.native.container-build=true
      QUARKUS_BRANCH: '2.13'
      QUARKUS_NATIVE_BUILDER_IMAGE: mandrel
      ADDITIONAL_TIMEOUT: 720
    ids:
    - native
    - prod
    - lts
  ecosystem:
    auto_generation: false
    ids:
    - ecosystem
productized_branch: false
disable:
  triggers: true
repositories:
- name: optaplanner
  branch: 9.35.x
git:
  author:
    name: kiegroup
    credentials_id: kie-ci
    token_credentials_id: kie-ci3-token
  bot_author:
    name: bsig-gh-bot
    credentials_id: bsig-gh-bot
  fork_author:
    name: kie-ci
    credentials_id: kie-ci
  quarkus:
    author:
      name: quarkusio
      credentials_id: kie-ci
    branch: main
  jenkins_config_path: .ci/jenkins
buildchain_config:
  git:
    repository: optaplanner
    branch: main
    file_path: .ci/buildchain-config.yaml
maven:
  settings_file_id: kogito_release_settings
  nexus:
    release_url: https://repository.jboss.org/nexus
    release_repository: jboss-releases-repository
    staging_profile_url: https://repository.jboss.org/nexus/content/groups/kogito-public/
    staging_profile_id: 2161b7b8da0080
    build_promotion_profile_id: ea49ccd6f174
  artifacts_repository: ''
  pr_checks:
    repository:
      url: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/repositories/kogito-runtimes-pr-full-testing/
      creds_id: unpacks-zip-on-qa-nexus
cloud:
  image:
    registry_credentials: optaplanner-quay-token
    registry: quay.io
    namespace: optaplanner
    latest_git_branch: main
jenkins:
  email_creds_id: OPTAPLANNER_CI_EMAIL
  default_tools:
    jdk: kie-jdk17
    maven: kie-maven-3.8.7
