environments:
  native:
    env_vars:
      NATIVE: true
      BUILD_MVN_OPTS_CURRENT: -Dnative -Dquarkus.native.container-build=true
      ADDITIONAL_TIMEOUT: 720
    ids:
    - native
  quarkus-main:
    enabled: false
    env_vars:
      QUARKUS_BRANCH: main
    ids:
    - quarkus
  quarkus-branch:
    env_vars:
      QUARKUS_BRANCH: '2.16'
    ids:
    - quarkus
  ecosystem:
    auto_generation: false
    ids:
    - ecosystem
disable:
  triggers: true # TODO to set back
repositories:
- name: optaplanner
- name: optaplanner-quickstarts
# - name: optaplanner-website // Not migrated yet
- name: kie-benchmarks
  author:
    name: radtriste # TODO set back. Could not push to kiegroup
git:
  author:
    name: kiegroup
    credentials_id: kie-ci5
    token_credentials_id: kie-ci5-token
  fork_author:
    name: kie-ci
    credentials_id: kie-ci
  quarkus:
    author:
      name: quarkusio
      credentials_id: kie-ci
    branch: main
  jenkins_config_path: .ci/jenkins
buildchain_config:
  git:
    repository: optaplanner
    file_path: .ci/buildchain-config.yaml
maven:
  settings_file_id: kie-release-settings
  nexus:
    release_url: TO_DEFINE
    release_repository: TO_DEFINE
    staging_profile_url: TO_DEFINE
    staging_profile_id: TO_DEFINE
    build_promotion_profile_id: TO_DEFINE
  artifacts_repository: ''
cloud:
  image:
    registry_credentials: tradisso_registry_token # TODO set to `kogito-quay-token`
    registry: quay.io
    namespace: tradisso
    latest_git_branch: main
jenkins:
  email_creds_id: KOGITO_CI_NOTIFICATION_EMAILS
  agent:
    docker:
      builder:
        image: quay.io/kiegroup/kogito-ci-build:latest
        args: -v /var/run/docker.sock:/var/run/docker.sock --group-add docker --group-add input --group-add render
  default_tools:
    jdk: jdk_17_latest
    maven: maven_3.8.6
    sonar_jdk: jdk_17_latest
