ecosystem:
  main_project: optaplanner
  projects:
  - name: optaplanner
    regexs:
    - opta.*
  - name: kie-benchmarks
    ignore_release: true
    regexs:
    - kie-benchmarks.*
git:
  branches:
  - name: main
    main_branch: true
    seed:
      branch: main
seed:
  config_file:
    git:
      repository: optaplanner
      author:
        name: kiegroup
        credentials_id: kie-ci5
      branch: main
    path: .ci/jenkins/config/branch.yaml
jenkins:
  email_creds_id: OPTAPLANNER_CI_EMAIL
