ecosystem:
  main_project: optaplanner
  projects:
  - name: optaplanner
    regexs:
    - opta.*
git:
  branches:
  - name: 9.x
    main_branch: true
    seed:
      branch: main
      config_file:
        git:
          branch: 9.x-dsl-config
  - name: 9.38.x
    seed:
      branch: seed-optaplanner-9.38.x
      config_file:
        git:
          branch: optaplanner-9.38.x
  - name: 9.40.x
    seed:
      branch: seed-optaplanner-9.40.x
      config_file:
        git:
          branch: optaplanner-9.40.x
  - name: 9.41.x
    seed:
      branch: seed-optaplanner-9.41.x
      config_file:
        git:
          branch: optaplanner-9.41.x
  main_branch: 9.x
seed:
  config_file:
    git:
      repository: optaplanner
      author:
        name: kiegroup
        credentials_id: kie-ci
      branch: 9.x-dsl-config
    path: .ci/jenkins/config/branch.yaml
jenkins:
  email_creds_id: OPTAPLANNER_CI_EMAIL
