name: "Quarkus ecosystem"
on:
  watch:
    types: [ started ]

  # For this CI to work, ECOSYSTEM_CI_TOKEN needs to contain a GitHub with rights to close the Quarkus issue that the user/bot has opened,
  # while 'ECOSYSTEM_CI_REPO_PATH' needs to be set to the corresponding path in the 'quarkusio/quarkus-ecosystem-ci' repository

env:
  ECOSYSTEM_CI_REPO: quarkusio/quarkus-ecosystem-ci
  ECOSYSTEM_CI_REPO_FILE: context.yaml

  #########################
  # Repo specific setting #
  #########################

  ECOSYSTEM_CI_REPO_PATH: optaplanner # a directory inside the ${ECOSYSTEM_CI_REPO}

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 11 ]
        maven-version: [ '3.8.7' ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    if: github.actor == 'quarkusbot'
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - Maven
    steps:
      - name: Install yq
        run: sudo add-apt-repository ppa:rmescandon/yq && sudo apt update && sudo apt install yq -y

      - name: Java and Maven Setup
        uses: apache/incubator-kie-kogito-pipelines/.ci/actions/maven@main
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
          cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: current-repo
          ref: main

      - name: Checkout Ecosystem
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ECOSYSTEM_CI_REPO }}
          ref: main
          path: ecosystem-ci

      - name: Setup and Run Tests
        run: ./ecosystem-ci/setup-and-test
        env:
          ECOSYSTEM_CI_TOKEN: ${{ secrets.ECOSYSTEM_CI_TOKEN }}
